from pydantic import BaseModel, Field, validator
from typing import Optional, List, Dict, Any
from datetime import datetime
from app.models.issue import (
    IssueType, IssueStatus, IssueStatusEnum, Priority,
    EscalationLevel, ActivityType
)
from app.schemas.base import PaginationInfo


# Base Issue Schema
class IssueBase(BaseModel):
    issue: str = Field(..., min_length=1, max_length=255, description="Issue name/title")
    type: IssueType
    description: Optional[str] = None
    property_id: Optional[int] = None
    assigned_to_id: Optional[int] = None
    priority: Priority = Priority.MEDIUM
    attachments: Optional[List[str]] = Field(default_factory=list)


# Schema for creating a new issue
class IssueCreate(IssueBase):
    created_by_id: int
    issue_status: IssueStatusEnum = IssueStatusEnum.OPEN
    # issue_code is auto-generated by system based on type (CMP-#### for COMPLAINT, TKT-#### for SUPPORT)


# Schema for updating an issue
class IssueUpdate(BaseModel):
    issue: Optional[str] = Field(None, min_length=1, max_length=255)
    type: Optional[IssueType] = None
    description: Optional[str] = None
    property_id: Optional[int] = None
    assigned_to_id: Optional[int] = None
    status: Optional[IssueStatus] = None
    issue_status: Optional[IssueStatusEnum] = None
    priority: Optional[Priority] = None
    attachments: Optional[List[str]] = None


# Schema for issue status update
class IssueStatusUpdate(BaseModel):
    issue_status: IssueStatusEnum
    description: Optional[str] = None


# Schema for issue assignment
class IssueAssignmentUpdate(BaseModel):
    assigned_to_id: Optional[int] = None


# Schema for priority update
class IssuePriorityUpdate(BaseModel):
    priority: Priority


# Schema for returning an issue
class IssueResponse(IssueBase):
    id: int
    issue_code: str = Field(..., description="Auto-generated by system: CMP-#### for COMPLAINT, TKT-#### for SUPPORT")
    created_by_id: int
    status: IssueStatus
    issue_status: IssueStatusEnum
    created_on: datetime
    updated_at: datetime
    
    class Config:
        orm_mode = True
        from_attributes = True


# Schema for issue with relationships
class IssueDetailResponse(IssueResponse):
    created_by_name: Optional[str] = None
    assigned_to_name: Optional[str] = None
    property_name: Optional[str] = None
    activities_count: int = 0
    escalations_count: int = 0
    
    class Config:
        orm_mode = True
        from_attributes = True


# Issue Activity Schemas
class IssueActivityBase(BaseModel):
    activity_type: ActivityType
    description: Optional[str] = None
    old_value: Optional[str] = None
    new_value: Optional[str] = None
    activity_metadata: Optional[Dict[str, Any]] = None


class IssueActivityCreate(IssueActivityBase):
    performed_by_id: int
    # issue_id comes from URL path, not request body


class IssueActivityResponse(IssueActivityBase):
    id: int
    issue_id: int
    performed_by_id: int
    performed_by_name: Optional[str] = None
    created_at: datetime
    
    class Config:
        orm_mode = True
        from_attributes = True


# Issue Escalation Schemas
class IssueEscalationBase(BaseModel):
    escalation_level: EscalationLevel
    reason: Optional[str] = None
    notes: Optional[str] = None


class IssueEscalationCreate(IssueEscalationBase):
    escalated_by_id: int
    escalated_to_id: int
    # issue_id comes from URL path, not request body


class IssueEscalationUpdate(BaseModel):
    resolved: Optional[bool] = None
    notes: Optional[str] = None
    resolved_by_id: Optional[int] = None


class IssueEscalationResponse(IssueEscalationBase):
    id: int
    issue_id: int
    escalated_by_id: int
    escalated_by_name: Optional[str] = None
    escalated_to_id: int
    escalated_to_name: Optional[str] = None
    resolved: bool
    resolved_at: Optional[datetime] = None
    resolved_by_id: Optional[int] = None
    resolved_by_name: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    
    class Config:
        orm_mode = True
        from_attributes = True


# Search and Filter Schemas
class IssueSearchRequest(BaseModel):
    page: int = Field(1, ge=1)
    limit: int = Field(10, ge=1, le=100)
    type: Optional[IssueType] = None
    status: Optional[IssueStatus] = None
    issue_status: Optional[IssueStatusEnum] = None
    priority: Optional[Priority] = None
    created_by_id: Optional[int] = None
    assigned_to_id: Optional[int] = None
    property_id: Optional[int] = None
    issue: Optional[str] = None  # Search by issue name


class IssueSearchResponse(BaseModel):
    status: str = "success"
    data: List[IssueDetailResponse]
    pagination: PaginationInfo


# API Response Models
class IssueCreateAPIResponse(BaseModel):
    """Response schema for issue creation"""
    status: str = "success"
    data: IssueDetailResponse
    message: str = "Issue created successfully"


class IssueListAPIResponse(BaseModel):
    """Response schema for issue list endpoints"""
    status: str = "success"
    data: List[IssueDetailResponse]
    message: str = "Issues retrieved successfully"


class IssueGetAPIResponse(BaseModel):
    """Response schema for single issue retrieval"""
    status: str = "success"
    data: IssueDetailResponse
    message: str = "Issue retrieved successfully"


class IssueUpdateAPIResponse(BaseModel):
    """Response schema for issue updates"""
    status: str = "success"
    data: IssueDetailResponse
    message: str = "Issue updated successfully"


class IssueDeleteAPIResponse(BaseModel):
    """Response schema for issue deletion"""
    status: str = "success"
    data: Dict[str, Any]
    message: str = "Issue deleted successfully"


class IssueStatusUpdateAPIResponse(BaseModel):
    """Response schema for issue status updates"""
    status: str = "success"
    data: IssueDetailResponse
    message: str = "Issue status updated successfully"


class IssueActivityCreateAPIResponse(BaseModel):
    """Response schema for activity creation"""
    status: str = "success"
    data: IssueActivityResponse
    message: str = "Activity logged successfully"


class IssueActivityListAPIResponse(BaseModel):
    """Response schema for activity list"""
    status: str = "success"
    data: List[IssueActivityResponse]
    message: str = "Activities retrieved successfully"


class IssueEscalationCreateAPIResponse(BaseModel):
    """Response schema for escalation creation"""
    status: str = "success"
    data: IssueEscalationResponse
    message: str = "Issue escalated successfully"


class IssueEscalationListAPIResponse(BaseModel):
    """Response schema for escalation list"""
    status: str = "success"
    data: List[IssueEscalationResponse]
    message: str = "Escalations retrieved successfully"


class IssueEscalationUpdateAPIResponse(BaseModel):
    """Response schema for escalation update"""
    status: str = "success"
    data: IssueEscalationResponse
    message: str = "Escalation updated successfully"

